### PR TITLE
Bug Fixes

### LINKED ISSUE #138: The Legend Box in PieChart does not work with all resolutions
The Legend Box in PieChart does not work with all resolutions.
Needs further Tweaking of the UI
image

### LINKED ISSUE #140: Add limit to the Protein, Carb and Fat to prevent integer overflow
Add limit to the Protein, Carb and Fat to prevent integer overflow.
Add the limit to all commands that can make food / edit food

### LINKED ISSUE #141: Delete is not relative to the current filtered list

### PR DESCRIPTION
**Pull request by Jh123x**
Logic Bug fixes
- [x] Update Usage of Paths.get to not use hardcoded delimiters
- [x] Made more variables final
- [x] Shorten code for the predicate in Version
- [x] Fix bug where delete is not relative to the filtered list
- [x] Lock MacroNutrient Values to 0 =< x < 1000 to prevent integer overflow

GUI fixes
- [x] Integer overflow for summary
    - Use Long instead of int to combat integer overflow
- [x] Legend not showing correctly
    - Made use of string padding
- [ ] <s>Graph refreshing every time something is entered <\s>
    - A feature instead of a bug.
    - Introduces more weird bugs.

### CODE REVIEW

**Review by aidoxe-123 — APPROVED** [review]
LGTM.

File: src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java [hunk 1]
```diff
@@ -5,7 +5,7 @@
 
 public abstract class Macronutrient {
     public static final String MESSAGE_CONSTRAINTS = "values should only contain positive numbers";
-    private static final String VALIDATION_REGEX = "(\\d)+";
+    private static final String VALIDATION_REGEX = "(\\d){1,3}";
```
Comment (JoeyChenSmart) [inline src/main/java/jimmy/mcgymmy/model/food/Macronutrient.java:8]: Alternatively if we wanted to cap it at 5000 we can do "[012345]?(\\d){1,3}" or sth

File: src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java [hunk 2]
```diff
@@ -50,14 +50,19 @@ public McGymmyParser(MacroList macroList) {
...
+            if (commandName.equals("macro")) {
+                return parseCreateMacro(text);
+            } else if (this.macroList.hasMacro(commandName)) {
+                return this.parseRunMacro(commandName, headTail.getTail());
+            } else if (this.primitiveCommandParser.hasCommand(commandName)) {
+                return this.primitiveCommandParser.parsePrimitiveCommand(commandName, headTail.getTail());
+            } else {
+                throw new ParseException(Messages.MESSAGE_UNKNOWN_COMMAND);
+            }
+        } catch (IllegalArgumentException e) {
```
Comment (JoeyChenSmart) [inline src/main/java/jimmy/mcgymmy/logic/parser/McGymmyParser.java:63]: TODO will have to address this next time: each parsing function should catch this and rethrow as `ParseError`

**Review by JoeyChenSmart — APPROVED** [review]
